# Copyright 2022 Kubespider
# SPDX-License-Identifier: Apache-2.0

name: Kubespider latest image build for ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to ACR
      uses: aliyun/acr-login@v1
      with:
        login-server: https://registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Kubespider - build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: registry.cn-hangzhou.aliyuncs.com/jwcesign/kubespider:latest

    - name: youget-downloader - build and push
      uses: docker/build-push-action@v3
      with:
        context: ./downloaders/you-get/
        push: true
        tags: registry.cn-hangzhou.aliyuncs.com/jwcesign/youget-downloader:latest

    - name: ytdlp-downloader - build and push
      uses: docker/build-push-action@v3
      with:
        context: ./downloaders/yt-dlp/
        push: true
        tags: registry.cn-hangzhou.aliyuncs.com/jwcesign/ytdlp-downloader:latest
